// <auto-generated>
// This file is generated by SceneIdGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using Lighthouse.Scene;

namespace YourProduct.LighthouseGenerated
{
    public static class YourProductMainSceneId
    {
        public static readonly MainSceneId None = new MainSceneId(1, string.Empty);
        public static readonly MainSceneId FirstScene = new MainSceneId(2, "FirstScene");

        public static ReadOnlySpan<MainSceneId> All
        {
            get
            {
                return new MainSceneId[]
                {
                    None,
                    FirstScene,
                };
            }
        }
    }
}
